name: CUPS
version: "1.6"
slug: cupsik
description: A CUPS print server with working AirPrint
arch:
  - amd64
  - aarch64
homeassistant_api: true
usb: true
init: false
startup: application
panel_icon: mdi:printer
panel_admin: false
boot: auto
legacy: true
ingress: true
ingress_port: 631
watchdog: http://[HOST]:[PORT:631]/
host_network: true
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: For other devices on the local network to print to this server
  631/udp: For other devices on the local network to print to this server
map:
  - addon_config:rw
